---
title: "Merge samples total cells"
author: "Mechthild Lütge"
date: "24 July 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(ggsci)
  library(pheatmap)
  library(ggpubr)
})

```

## set dir
```{r set dir}
basedir <- here()
seurat <- readRDS(file = paste0(basedir,
                              "/data/MuHeart_totalCells_integrated_seurat.rds"))
Idents(seurat) <- seurat$integrated_snn_res.0.4


## remove two contaminating clusters and rerun dim reductions
## cluster 8 (dying cells, a lot of ribosomal genes)
## cluster 17 (erythrocytes (Fech, Bpgm, Snca))
seurat <- subset(seurat, idents = c("8", "17"), invert=T)

DefaultAssay(object = seurat) <- "integrated"
seurat <- RunPCA(object = seurat, npcs = 20, verbose = FALSE)
seurat <- RunTSNE(object = seurat, reduction = "pca", dims = 1:20)
seurat <- RunUMAP(object = seurat, reduction = "pca", dims = 1:20)
DefaultAssay(object = seurat) <- "RNA"


```



## color vectors
```{r colVec}

colPal <- pal_igv()(length(levels(seurat)))
colGrp <- pal_jama()(length(unique(seurat$grp)))
colAge <- pal_uchicago()(length(unique(seurat$age)))
colStype <- pal_aaas()(length(unique(seurat$seqType)))
colDat <- c(pal_npg()(10),
            pal_futurama()(10))[1:(length(unique(seurat$dataset)))]

  
names(colPal) <- levels(seurat)
names(colGrp) <- unique(seurat$grp)
names(colAge) <- unique(seurat$age)
names(colStype) <- unique(seurat$seqType)
names(colDat) <- unique(seurat$dataset)
```


## vis data {.tabset}
### clusters
```{r vis cluster}

DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### group
```{r vis grp}

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```


### Sample
```{r vis sample}

DimPlot(seurat, reduction = "umap", group.by = "dataset", cols=colDat)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### Age
```{r vis age}

DimPlot(seurat, reduction = "umap", group.by = "age", cols=colAge)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### SeqType
```{r vis seqType}

DimPlot(seurat, reduction = "umap", group.by = "seqType", cols=colStype)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

## assign labels {.tabset}
```{r assign labels}

seurat$label <- "other"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("11"))] <- "Macrophages"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("18"))] <- "Bcells"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("2"))] <- "MacrophagesMonocytes"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("7"))] <- "Tcells"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("9"))] <- "NKcells"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("14"))] <- "Neutrophils"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("15"))] <- "DCs"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("16"))] <- "proliferating"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("19"))] <- "glialCells"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("20"))] <- "smc"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("1","3","4","13"))] <-
  "Fibroblasts"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("5", "10"))] <- "Cardiomyocytes"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("0", "12"))] <- "Endothelial"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("6"))] <- "Perivascular"
seurat$label[which(seurat$integrated_snn_res.0.4 %in% c("21"))] <- "capEndothelial"

colLab <- pal_igv()(length(unique(seurat$label)))
names(colLab) <- unique(seurat$label)
```


### label
```{r vis label}

DimPlot(seurat, reduction = "umap", group.by = "label", cols=colLab)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### label split by seqType
```{r vis label split seq, fig.height=3.5, fig.width=7}

DimPlot(seurat, reduction = "umap", group.by = "label", cols=colLab,
        split.by = "seqType")+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### label split by grp
```{r vis label split grp, fig.height=3.5, fig.width=7}

DimPlot(seurat, reduction = "umap", group.by = "label", cols=colLab,
        split.by = "grp")+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```



### cnt Tab
```{r cnts par lab per seqType}

table(seurat$label, seurat$seqType)

```


## cw DE genes {.tabset} 

### 4 weeks

```{r cw DE genes 4wk}

seuratSub <- subset(seurat, age == "4wk")
Idents(seuratSub) <- seuratSub$grp
grpVec <- unique(seuratSub$label)

clustDE <- lapply(grpVec, function(grp){
  grpSub <- unique(seuratSub$label)[which(
    unique(seuratSub$label)==grp)]
  seuratSub2 <- subset(seuratSub, label == grpSub)
  DEgenes <-FindAllMarkers(seuratSub2, only.pos=T, logfc.threshold = 0.25,
                           min.pct = 0.1)
  if(nrow(DEgenes)>1){
    DEgenes <- DEgenes %>% filter(p_val_adj<0.01) %>%
      mutate(group=paste0(grp, "_", cluster))
    }
})

names(clustDE) <- grpVec

clustDE_Dat4 <- data.frame(do.call("rbind", clustDE))
```


### 8 weeks

```{r cw DE genes 8wk}

seuratSub <- subset(seurat, age == "8wk")
Idents(seuratSub) <- seuratSub$grp
grpVec <- unique(seuratSub$label)

clustDE <- lapply(grpVec, function(grp){
  grpSub <- unique(seuratSub$label)[which(
    unique(seuratSub$label)==grp)]
  seuratSub2 <- subset(seuratSub, label == grpSub)
  DEgenes <-FindAllMarkers(seuratSub2, only.pos=T, logfc.threshold = 0.25,
                           min.pct = 0.1)
  if(nrow(DEgenes)>1){
    DEgenes <- DEgenes %>% filter(p_val_adj<0.01) %>%
      mutate(group=paste0(grp, "_", cluster))
    }
})

names(clustDE) <- grpVec


clustDE_Dat8 <- data.frame(do.call("rbind", clustDE))
```


## vis BMPs {.tabset}
### Bmp2
```{r vis Bmp2}
p <- FeaturePlot(seurat, reduction = "umap", 
            features = "ENSMUSG00000027358.Bmp2",
            cols=c("lightgrey", "darkred"),
            order = T)+
  theme(legend.position="right")
p

```

### Bmp4
```{r vis Bmp4}
p <- FeaturePlot(seurat, reduction = "umap", 
            features = "ENSMUSG00000021835.Bmp4",
            cols=c("lightgrey", "darkred"),
            order = T)+
  theme(legend.position="right")
p

```

### Bmpr1a
```{r vis Bmpr1a}
p <- FeaturePlot(seurat, reduction = "umap", 
            features = "ENSMUSG00000021796.Bmpr1a",
            cols=c("lightgrey", "darkred"),
            order = T)+
  theme(legend.position="right")
p

```

### Bmpr2
```{r vis Bmpr2}
p <- FeaturePlot(seurat, reduction = "umap", 
            features = "ENSMUSG00000067336.Bmpr2",
            cols=c("lightgrey", "darkred"),
            order = T)+
  theme(legend.position="right")
p

```


## save integrated objects
```{r save int}
saveRDS(seurat, file = paste0(basedir,
                      "/data/MuHeart_totalCells_integratedLabeled_seurat.rds"))

write.table(clustDE_Dat4,
            file=paste0(basedir,
              "/data/MuHeart_totalCells_integratedLabeled_4wks_cwDEGenes.txt"),
            row.names = FALSE, col.names = TRUE, quote = FALSE, sep = "\t")

write.table(clustDE_Dat8,
            file=paste0(basedir,
              "/data/MuHeart_totalCells_integratedLabeled_8wks_cwDEGenes.txt"),
            row.names = FALSE, col.names = TRUE, quote = FALSE, sep = "\t")

```



## session info
```{r session info}
sessionInfo()
date()
```




