---
title: "Pathway analysis Fibroblasts"
author: "Mechthild Lütge"
date: "24 July 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(ggsci)
  library(pheatmap)
  library(ggpubr)
  library(clusterProfiler)
  library(org.Mm.eg.db)
  library(DOSE)
  library(enrichplot)
})

```

## set dir
```{r set dir}
basedir <- here()
seurat <- readRDS(file = paste0(basedir, 
                                "/data/TCRM_all10samplesMerged_seurat.rds"))

seurat$time_plus_grp <- paste0(seurat$time, "_", seurat$grp)

```



## color vectors
```{r colVec}

colPal <- pal_igv()(length(levels(seurat)))
colGrp <- pal_jama()(length(unique(seurat$grp)))
colSmp <- c(pal_uchicago()(8), pal_npg()(8))[1:length(unique(seurat$dataset))]
colTime <- pal_npg()(length(unique(seurat$time)))

names(colPal) <- levels(seurat)
names(colGrp) <- unique(seurat$grp)
names(colSmp) <- unique(seurat$dataset)
names(colTime) <- unique(seurat$time)

```


## vis data {.tabset}
### clusters
```{r vis cluster}

DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### group
```{r vis grp}

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```


### Sample
```{r vis sample}

DimPlot(seurat, reduction = "umap", group.by = "dataset", cols=colSmp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### Time
```{r vis time}

DimPlot(seurat, reduction = "umap", group.by = "time", cols=colTime)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```



## overall DE genes {.tabset} 

```{r overall DE genes}

Idents(seurat) <- seurat$grp
DEgenes <-FindAllMarkers(seurat, only.pos=T, logfc.threshold = 0.25,
                           min.pct = 0.1)

```

### GSEA clusterProfiler 

```{r GSEA clusterprofiler, fig.height=6, fig.width=12}

grpVec <- unique(seurat$grp)
GOcons <- lapply(grpVec, function(cl){
  DEgenesSub <- DEgenes %>% 
    filter(cluster == cl) %>% mutate(ENS=gsub("\\..*$", "", gene)) %>% 
    slice_min(., p_val_adj, n=250)
  egoSS <- enrichGO(gene      = unique(DEgenesSub$ENS),
                OrgDb         = org.Mm.eg.db,
                keyType       = 'ENSEMBL',
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.05)
  egoSS <- setReadable(egoSS, OrgDb = org.Mm.eg.db)
  egoSSres <- egoSS@result %>% filter(p.adjust < 0.05) %>% 
    mutate(subset=cl)
})

names(GOcons) <- grpVec

```



```{r vis summary, fig.height=5, fig.width=10}

## table to select pathways
GOconsDat <- do.call("rbind", GOcons)
write.table(GOconsDat, quote=F, row.names = T, col.names = T, sep= "\t",
            file = paste0(basedir,"/data/GSEA/MuHeart_allFibroblasts_OverallDE",
            "_GO.txt"))
	

selGO <- c(rownames(GOconsDat)[1:5], "Ccl19.GO:0071773", "Ccl19.GO:0030198",
           "Ccl19.GO:0043062")


GOconsDat <- do.call("rbind", GOcons) %>% rownames_to_column(., var="IDlab") %>% 
  filter(IDlab %in% selGO)
GOconsDat$subset <- factor(GOconsDat$subset, levels=c("TCRMxCcl19", "Ccl19"))
GOconsDat <- GOconsDat %>% 
  arrange(., Count) %>% arrange(., subset) %>%
  mutate(nom=as.numeric(gsub("\\/.*", "", GeneRatio))) %>% 
  mutate(denom=as.numeric(gsub(".*\\/", "", GeneRatio))) %>% 
  mutate(geneRatio=nom/denom) %>% 
  mutate(one_minPadjust=(1-qvalue))


GOconsDat <- GOconsDat %>% mutate(qscore=-log(p.adjust, base=10)) %>% 
  mutate(DescriptionLab = paste0(subset, ": ", Description))
p <- ggbarplot(GOconsDat, x = "DescriptionLab", y = "qscore",
          fill = "subset",               
          color = "subset",            
          palette = colGrp,            
          sort.val = "asc",           
          sort.by.groups = TRUE      
          #x.text.angle = 90           
          ) + 
  rotate()
p


GOconsDatmod <- GOconsDat %>% 
  mutate(pAdj = ifelse(p.adjust<0.00001, 0.00001, p.adjust)) %>% 
  mutate(Qscore=-log(pAdj, base=10)) %>% 
  mutate(qValGrp = ifelse(subset=="Ccl19", -Qscore, Qscore))

p <- ggbarplot(GOconsDatmod, x = "DescriptionLab", y = "qValGrp",
          fill = "subset",               
          color = "subset",            
          palette = colGrp,            
          sort.val = "asc",           
          sort.by.groups = TRUE      
          #x.text.angle = 90           
          ) + 
  rotate()
p


```



## session info
```{r session info}
sessionInfo()
date()
```




