---
title: "Merge samples total cells"
author: "Mechthild Lütge"
date: "24 July 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(ggsci)
  library(pheatmap)
  library(ggpubr)
  library(clusterProfiler)
  library(org.Mm.eg.db)
  library(DOSE)
  library(enrichplot)
})

```

## set dir
```{r set dir}
basedir <- here()
seurat <- readRDS(file = paste0(basedir,
                      "/data/MuHeart_totalCells_integratedLabeled_seurat.rds"))
Idents(seurat) <- seurat$label

```



## color vectors
```{r colVec}

colPal <- pal_igv()(length(levels(seurat)))
colGrp <- pal_jama()(length(unique(seurat$grp)))
colAge <- pal_uchicago()(length(unique(seurat$age)))
colStype <- pal_aaas()(length(unique(seurat$seqType)))
colDat <- c(pal_npg()(10),
            pal_futurama()(10))[1:(length(unique(seurat$dataset)))]

names(colPal) <- levels(seurat)
names(colGrp) <- unique(seurat$grp)
names(colAge) <- unique(seurat$age)
names(colStype) <- unique(seurat$seqType)
names(colDat) <- unique(seurat$dataset)

colLab <- c("#5050FF", "#CE3D32", "#749B58", "#F0E685",
            "#466983", "#BA6388", "#5DB1DD", "#802268",
            "#6BD76B", "#D595A7", "#924822", "#837B8D",
            "#C75127", "#D58F5C", "#7A65A5", "#E4AF69")

names(colLab) <- c("InfMonos", "Tcells", "Endothelial", "Macrophages",
                   "Fibroblasts", "DCs", "NKcells", "Perivascular",
                   "Neutrophils", "Bcells", "Cardiomyocytes", "proliferating",
                   "pDCs", "endocardialEndothelial", "Eosinophils",
                   "GlialCells")


```


## vis data {.tabset}
### clusters
```{r vis cluster}

DimPlot(seurat, reduction = "umap", group.by = "label", cols=colLab)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### group
```{r vis grp}

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```


### Sample
```{r vis sample}

DimPlot(seurat, reduction = "umap", group.by = "dataset", cols=colDat)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### Age
```{r vis age}

DimPlot(seurat, reduction = "umap", group.by = "age", cols=colAge)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### SeqType
```{r vis seqType}

DimPlot(seurat, reduction = "umap", group.by = "seqType", cols=colStype)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


## overall DE genes {.tabset} 

```{r overall DE genes}

Idents(seurat) <- seurat$grp
DEgenes <-FindAllMarkers(seurat, only.pos=T, logfc.threshold = 0.25,
                           min.pct = 0.1)

```

### GSEA clusterProfiler 

```{r GSEA clusterprofiler, fig.height=6, fig.width=12}

grpVec <- unique(seurat$grp)
GOcons <- lapply(grpVec, function(cl){
  DEgenesSub <- DEgenes %>% 
    filter(cluster == cl) %>% mutate(ENS=gsub("\\..*$", "", gene)) %>% 
    slice_min(., p_val_adj, n=250)
  egoSS <- enrichGO(gene      = unique(DEgenesSub$ENS),
                OrgDb         = org.Mm.eg.db,
                keyType       = 'ENSEMBL',
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.05)
  egoSS <- setReadable(egoSS, OrgDb = org.Mm.eg.db)
  egoSSres <- egoSS@result %>% filter(p.adjust < 0.05) %>% 
    mutate(subset=cl)
})

names(GOcons) <- grpVec

```



```{r vis summary, fig.height=5, fig.width=10}

## table to select pathways
GOconsDat <- do.call("rbind", GOcons)
write.table(GOconsDat, quote=F, row.names = T, col.names = T, sep= "\t",
            file = paste0(basedir, "/data/GSEA/MuHeart_totalCells_OverallDE",
            "_GO.txt"))
	

selGO <- read_tsv(paste0(basedir,"/data/GSEA/selGO_overall.txt"))
GOconsDat <- GOconsDat %>% filter(ID %in% selGO$GOterm) %>% 
  mutate(Grp=ifelse(subset=="control", "Ctrl", "TCRM"))

grpVec <- unique(selGO$Grp)
lapply(grpVec, function(grp){
  selGODat <- GOconsDat %>% filter(Grp == grp)
  selGODat <- selGODat %>% mutate(qscore=-log(p.adjust, base=10)) 
  p <- ggbarplot(selGODat, x = "Description", y = "qscore",
          fill = "subset",               
          color = "subset",            
          palette = colGrp,            
          sort.val = "asc",           
          sort.by.groups = TRUE      
          #x.text.angle = 90           
          ) + 
  rotate()
p
})


```

## scatterplot overall DE genes
```{r scatterplot overall DEgenes, fig.height=3.5, fig.width=4}

## scatterplot
## in red are all genes with an adjusted p_val < 0.01 and avg_logFC >0.25

################################################################################
### include only genes expressed in at least 10 % of cells in one condition ####
################################################################################

allID <- seurat
Idents(allID) <-allID$grp
avg.allID <- AverageExpression(allID, group.by="grp",
                               show.progress = FALSE)
avg.allID <- data.frame(log1p(avg.allID$RNA)) %>% 
  rownames_to_column(var="gene")

## expression frequency
GeneFreqSel <- as.data.frame(GetAssayData(allID, assay = "RNA",
                                          slot = "data")) %>%
  tibble::rownames_to_column(var="gene") %>% mutate(count=rowSums(.!=0)-1) %>%
  mutate(countFreq=count/ncol(allID)) %>%
  dplyr::select(gene,count, countFreq) %>%
  dplyr::filter(countFreq>=0.1)

signGenes2 <- DEgenes %>% dplyr::filter(p_val_adj<0.01 & (avg_log2FC > 0.25)) 

# genes.to.label <- DEgenes %>% group_by(.,cluster) %>% 
#   slice_max(avg_log2FC, n=7) %>% mutate(labelNam=gsub("^.*\\.", "", gene))

genes.to.label <- read_tsv(file = paste0(basedir, "/data/GSEA/",
                                         "selGenesScatterplotTotalDE.txt"))

avg.allID <- avg.allID %>% mutate(labelNam=gsub("^.*\\.", "", gene)) %>%
  mutate(colourGrp=ifelse(labelNam %in% genes.to.label$labelNam, "lab",
                          ifelse(gene%in%signGenes2$gene, "sig", "notSig"))) %>%
  dplyr::filter(gene%in%GeneFreqSel$gene)


p_allID <- ggscatter(avg.allID, x="control", y="TCRM",
                    color = "colourGrp",
                    palette = c("#660000", "#808080", "#FF3333"),
                    label="labelNam",
                    label.select = genes.to.label$labelNam,
                    repel = F,
                    label.rectangle=F,
                    xlab="control",
                    ylab = "TCRM",
                    title="",
                    legend="none",
                    font.label=6,
                    alpha=0.9,
                    size=0.5)


p_allID 

p_allID <- ggscatter(avg.allID, x="control", y="TCRM",
                    color = "colourGrp",
                    palette = c("#660000", "#808080", "#FF3333"),
                    label=NULL,
                    repel = F,
                    label.rectangle=F,
                    xlab="control",
                    ylab = "TCRM",
                    title="",
                    legend="none",
                    font.label=6,
                    alpha=0.9,
                    size=0.5)


p_allID 

```


## DE genes Cardiomyocytes {.tabset} 

```{r DE genes CM}
seuratSub <- subset(seurat, label == "Cardiomyocytes")
Idents(seuratSub) <- seuratSub$grp
DEgenes <-FindAllMarkers(seuratSub, only.pos=T, logfc.threshold = 0.25,
                           min.pct = 0.1)

```

### GSEA clusterProfiler

```{r GSEA clusterprofiler CM, fig.height=6, fig.width=12}

grpVec <- unique(seuratSub$grp)
GOcons <- lapply(grpVec, function(cl){
  DEgenesSub <- DEgenes %>% 
    filter(cluster == cl) %>% mutate(ENS=gsub("\\..*$", "", gene)) %>% 
    slice_min(., p_val_adj, n=250)
  egoSS <- enrichGO(gene      = unique(DEgenesSub$ENS),
                OrgDb         = org.Mm.eg.db,
                keyType       = 'ENSEMBL',
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.05)
  egoSS <- setReadable(egoSS, OrgDb = org.Mm.eg.db)
  egoSSres <- egoSS@result %>% filter(p.adjust < 0.05) %>% 
    mutate(subset=cl)
})

names(GOcons) <- grpVec

```


```{r vis summary CM, fig.height=5, fig.width=10}

## table to select pathways
GOconsDat <- do.call("rbind", GOcons)
write.table(GOconsDat, quote=F, row.names = T, col.names = T, sep= "\t",
            file = paste0(basedir, "/data/GSEA/MuHeart_Cardiomyocytes_DE",
            "_GO.txt"))
	

selGO <- read_tsv(paste0(basedir,"/data/GSEA/selGO_Cardiomyocytes.txt"))
GOconsDat <- GOconsDat %>% filter(ID %in% selGO$GOterm) %>% 
  mutate(Grp=ifelse(subset=="control", "Ctrl", "TCRM"))

grpVec <- unique(selGO$Grp)
lapply(grpVec, function(grp){
  selGODat <- GOconsDat %>% filter(Grp == grp)
  selGODat <- selGODat %>% mutate(qscore=-log(p.adjust, base=10)) 
  p <- ggbarplot(selGODat, x = "Description", y = "qscore",
          fill = "subset",               
          color = "subset",            
          palette = colGrp,            
          sort.val = "asc",           
          sort.by.groups = TRUE      
          #x.text.angle = 90           
          ) + 
  rotate()
p
})

```



## session info
```{r session info}
sessionInfo()
date()
```




