---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

### Cardiac Fibroblasts:  
merge and visualize fibroblast data: [link](mergeAndVisData_TCRM_2.html)  
characterize fibroblasts: [link](characterizeFibroblasts.html)  
pseudotime analysis cardiac fibroblasts: [link](pseudotimeAnalysisFibroblasts.html)  
characterize eyfp only fibroblasts: [link](characterizeEyfpFibroblasts.html)  
characterize eyfp only fibroblasts wo 12wks: [link](charcaterizeFibroblastwo12wk.html)  
GSEA Fibroblasts: [link](GSEAfibroblasts.html)  
DE genes TCRM vs WT Fibroblasts wo 12k: [link](DEgenesFibroblastwo12wk.html)  
visualize marker genes Fibroblasts: [link](visClusterMarkerFibroblasts_wo12weeks.html)  

### Hematopoietic cells:  
merge CD45+ cells: [link](mergeCD45cells.html)  
visualize activation CD45+ cells:  [link](visGrps_CD45Data.html)  

### Total cells:  
merge total cell murine heart: [link](mergeTotalCells_MuHeart_plusTreat.html)  
characterize total cells murine heart: [link](characterizeTotalCellsHumanHeart.html)  
vis BMPs total cells murine heart: [link](visBMPsTCRMvsCtrl.html)  
GSEA total cells: [link](GSEAtotalCells.html)  
visualize total cells untreated: [link](visualizeTotalCellsUntreated.html)  
DE genes upon antibody treatment: [link](DEgenesTreatment.html)  
Reembedding Fibroblast: [link](reembeddingFibroWoTreatment.html)  
visualize gene signatures total cells untreated: [link](visSignaturesTotalCellsUntreated.html)  
visualize marker genes total cells: [link](visClusterMarkerTotalCells.html)  
DE genes Endothelial TCRM versus Ctrl: [link](DEgenesEndothelial_TCRMvsCtrl.html) 


### 14D102 Treatment:  
DE genes upon antibody treatment: [link](DEgenesTreatment.html)  
visualize gene signatures Fibroblasts only sc data: [link](visDMplusSignFibroTreatedOnly.html)  
visualize gene signatures Fibroblasts only sc data: [link](visDMplusSignFibroTreatedOnlySN.html)  
DE genes Endothelial 14D102 versus Isotype: [link](DEgenesEndothelial_14D102vsIsotype.html)  
vis BMPs 14D102 versus Isotype: [link](visBMPs14D102vsIsotype.html)  

### medLN data:  
analyse medLN balbc: [link](analyseMedLN_balbc.html)  
