---
title: "Merge samples"
author: "Mechthild Lütge"
date: "14 May 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(ggsci)
  library(ggpubr)
  library(pheatmap)
})

```

## set dir
```{r set dir}
basedir <- here()
metaDat <- read_tsv(paste0(basedir, "/metadata.txt"), col_names = T)

```


## load and assign samples
```{r load plus assign samples}

assignSamples <- function(smpNam, basedirSmp, smpGrp, smpBatch, smpTime){
  smpNamFull <- list.files(path = paste0(basedirSmp, "/data/"),
				 pattern = paste0(smpNam, ".*_seurat.rds"))
  seuratSmp <- readRDS(paste0(basedirSmp, "/data/", smpNamFull))
  seuratSmp$grp <- smpGrp
  seuratSmp$batch <- smpBatch
  seuratSmp$time <- smpTime
  return(seuratSmp)
}

####################################################################

for(i in 1:length(metaDat$Sample)){
  seuratX <- assignSamples(smpNam = metaDat$Sample[i],
                           basedirSmp = basedir,
                           smpGrp = metaDat$group[i],
                           smpBatch = metaDat$batch[i],
                           smpTime = metaDat$timepoint[i])
  if(exists("seurat")){
    seurat <- merge(x = seurat, y = seuratX, project = "TCRMxCcl19")
  }else{
    seurat <- seuratX
  }
}

remove(seuratX)

```



## run clustering and DR and remove contaminating cells
```{r clustering and DR}

seurat <- rerunSeurat3(seurat)
#seuratSub <- subset(seurat1, subset = `MGP-BALBcJ-G0026271.Grem1` >0) ## 5 cells
#seuratSub <- subset(seurat1, subset = `MGP-BALBcJ-G0026527.Bmp2` >0) ## 14104 cells

dat <- data.frame(table(seurat$dataset))
colnames(dat) <- c("dataset", "all")

seuratSub <- subset(seurat, subset = ENSMUSG00000074934.Grem1 >0) ## 5 cells
dat2 <- data.frame(table(seuratSub$dataset))
colnames(dat2) <- c("dataset", "Grem1")
dat <- dat %>% left_join(., dat2, by=c("dataset"))

seuratSub <- subset(seurat, subset = ENSMUSG00000050069.Grem2 >0) ## 292 cells
dat2 <- data.frame(table(seuratSub$dataset))
colnames(dat2) <- c("dataset", "Grem2")
dat <- dat %>% left_join(., dat2, by=c("dataset"))

seuratSub <- subset(seurat, subset = ENSMUSG00000027358.Bmp2 >0) ## 14104 cells
dat2 <- data.frame(table(seuratSub$dataset))
colnames(dat2) <- c("dataset", "Bmp2")
dat <- dat %>% left_join(., dat2, by=c("dataset"))

seuratSub <- subset(seurat, subset = ENSMUSG00000021835.Bmp4 >0) ## 37496 cells
dat2 <- data.frame(table(seuratSub$dataset))
colnames(dat2) <- c("dataset", "Bmp4")
dat <- dat %>% left_join(., dat2, by=c("dataset"))

seuratSub <- subset(seurat, subset = 	ENSMUSG00000021796.Bmpr1a >0) ## 31304 cells
dat2 <- data.frame(table(seuratSub$dataset))
colnames(dat2) <- c("dataset", "Bmpr1a")
dat <- dat %>% left_join(., dat2, by=c("dataset"))

seuratSub <- subset(seurat, subset = 	ENSMUSG00000052430.Bmpr1b >0) ## 193 cells
dat2 <- data.frame(table(seuratSub$dataset))
colnames(dat2) <- c("dataset", "Bmpr1b")
dat <- dat %>% left_join(., dat2, by=c("dataset"))

seuratSub <- subset(seurat, subset = ENSMUSG00000067336.Bmpr2 >0) ## 33577 cells
dat2 <- data.frame(table(seuratSub$dataset))
colnames(dat2) <- c("dataset", "Bmpr2")
dat <- dat %>% left_join(., dat2, by=c("dataset"))
dat[is.na(dat)] <-0

dat_fin <-  dat %>%
  bind_rows(summarise_all(., funs(if(is.numeric(.)) sum(.) else "total")))

knitr::kable(dat_fin)

## total 71484 cells

```

## check QC
```{r check QC}

datSet <- unique(seurat$dataset)
sceList <- lapply(datSet, function(datS){
  seuratSub <- subset(seurat, dataset==datS)
  sceSub <- as.SingleCellExperiment(seuratSub)
})
names(sceList) <- datSet

colDat <- pal_npg()(length(unique(seurat$dataset)))
names(colDat) <- unique(seurat$dataset)

sce <- as.SingleCellExperiment(seurat)

plotQC2 <- function(sce, feature){
  p <- gghistogram(data = as.data.frame(sce@colData),
              x=feature,
              bins=70,
              #title=unique(sce$dataset),
              fill = "dataset",
              palette = colDat,
              legend = "right")
  return(p)
}

plotQC3 <- function(sce, feature){
  p <- gghistogram(data = as.data.frame(sce@colData),
              x=feature,
              y = "..density..",
              bins=70,
              fill = "dataset",
              palette = colDat,
              add_density = TRUE,
              legend = "right")
  return(p)
}

plotQC2(sce, "total_counts")
plotQC3(sce, "total_counts")

plotQC2(sce, "total_features_by_counts")
plotQC3(sce, "total_features_by_counts")

plotQC2(sce, "pct_counts_Mt")
plotQC3(sce, "pct_counts_Mt")

plotQC2(sce, "pct_counts_in_top_500_features")
plotQC3(sce, "pct_counts_in_top_500_features")

plotQC2(sce, "pct_counts_endogenous")
plotQC3(sce, "pct_counts_endogenous")

plotQC2(sce, "total_features_by_counts_Mt")
plotQC3(sce, "total_features_by_counts_Mt")

plotQC2(sce, "total_counts_Mt")
plotQC3(sce, "total_counts_Mt")

plotQC2(sce, "pct_counts_in_top_500_features_endogenous")
plotQC3(sce, "pct_counts_in_top_500_features_endogenous")


```


## color vectors
```{r colVec}

colPal <- pal_igv()(length(levels(seurat)))
colGrp <- pal_jama()(length(unique(seurat$grp)))
colSmp <- c(pal_uchicago()(8), pal_npg()(8))[1:length(unique(seurat$dataset))]
colTime <- pal_npg()(length(unique(seurat$time)))

names(colPal) <- levels(seurat)
names(colGrp) <- unique(seurat$grp)
names(colSmp) <- unique(seurat$dataset)
names(colTime) <- unique(seurat$time)

```


## vis data {.tabset}
### clusters
```{r vis cluster}
DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### group
```{r vis grp}

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```


### Sample
```{r vis sample}

DimPlot(seurat, reduction = "umap", group.by = "dataset", cols=colSmp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### batch
```{r vis batch}

DimPlot(seurat, reduction = "umap", group.by = "batch")+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### timepoint
```{r vis timepoint}

DimPlot(seurat, reduction = "umap", group.by = "time", cols=colTime)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```



## marker genes
```{r marker genes}

seurat_markers_all <- FindAllMarkers(object = seurat, assay ="RNA",
                                     only.pos = TRUE, min.pct = 0.25,
                                     logfc.threshold = 0.25,
                                     test.use = "wilcox")

```


```{r avg heatmap function, eval=T, include=FALSE}

avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  
  ## format gene names (depends on how gene list is inputed)
  selGenes <- selGenes %>% 
      mutate(labelNam = (str_split(gene, '\\.', simplify = T)[,2]))
  selGenes <- selGenes$labelNam
  
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
  annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                       colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
    dplyr::mutate(cond = gsub("(^[0-9]_?)","",col1)) %>%
    dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      cond = colVecCond,
      celltype=colVecIdent)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
    ordVec <- levels(seurat)
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0, cluster_rows = cr, 
         cluster_cols = cc,
         color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = annotation_col, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

```


## overall DE genes
```{r overall DE, fig.height=10, fig.width=6}

Idents(seurat) <- seurat$grp

DEgenes <- FindAllMarkers(object = seurat, assay ="RNA",
                                     only.pos = TRUE, min.pct = 0.25,
                                     logfc.threshold = 0.25,
                                     test.use = "wilcox")

### plot DE genes top 15 avg logFC
DEGenesAll <- DEgenes %>% group_by(cluster) %>% 
  top_n(15, avg_log2FC)

Idents(seurat) <- seurat$RNA_snn_res.0.4
avgHeatmap(seurat = seurat, selGenes = DEGenesAll,
                  colVecIdent = colPal, 
                  ordVec=levels(seurat),
                  gapVecR=NULL, gapVecC=NULL,cc=T,
                  cr=T, condCol=F)
```


## save objects
```{r save}
Idents(seurat) <- seurat$seurat_clusters
saveRDS(seurat, file = paste0(basedir, 
                              "/data/TCRM_all10samplesMerged_seurat.rds"))

write.table(seurat_markers_all,
            file=paste0(basedir, "/data/TCRM_all10samplesMerged_markerGenes.txt"),
            row.names = FALSE, col.names = TRUE, quote = FALSE, sep = "\t")

write.table(DEgenes,
            file=paste0(basedir, "/data/TCRM_all10samplesMerged_DEGenes.txt"),
            row.names = FALSE, col.names = TRUE, quote = FALSE, sep = "\t")

```


## session info
```{r session info}
sessionInfo()
date()
```




