---
title: "pseudotime analysis"
author: "Mechthild Lütge"
date: "6 Oct 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(slingshot)
  library(SingleCellExperiment)
  library(scales)
  library(grDevices)
  library(RColorBrewer)
  library(pheatmap)
  library(ggsci)
})

```

## set dir
```{r set dir}
basedir <- here()
seurat <- readRDS(file = paste0(basedir, 
                                "/data/TCRM_all10samplesMerged_seurat.rds"))

seurat$time_plus_grp <- paste0(seurat$time, "_", seurat$grp)
```

## color vectors
```{r colVec}

colPal <- pal_igv()(length(levels(seurat)))
colGrp <- pal_jama()(length(unique(seurat$grp)))
colSmp <- c(pal_uchicago()(8), pal_npg()(8))[1:length(unique(seurat$dataset))]
colTime <- pal_npg()(length(unique(seurat$time)))

names(colPal) <- levels(seurat)
names(colGrp) <- unique(seurat$grp)
names(colSmp) <- unique(seurat$dataset)
names(colTime) <- unique(seurat$time)

```

## vis data {.tabset}
### clusters
```{r vis cluster}
DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### group
```{r vis grp}

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```

### timepoint
```{r vis timepoint}

DimPlot(seurat, reduction = "umap", group.by = "time", cols=colTime)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### clustering res 0.25
```{r vis cluster res 0.25}

DimPlot(seurat, reduction = "umap", group.by = "RNA_snn_res.0.4", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```




## run slingshot {.tabset}
```{r slinshot}

sce <- as.SingleCellExperiment(seurat)
sce <- slingshot(sce, clusterLabels = 'RNA_snn_res.0.4', reducedDim = 'UMAP',
                 approx_points = 100, stretch = 0,
                 thresh = 0.001, omega = 10, extend = "n")

colPalDat <- data.frame(Color=colPal, cl=names(colPal))
colDat <- data.frame(cl=sce$seurat_clusters) %>% 
  left_join(., colPalDat, by="cl")


```


### plot lineages
```{r plot lineages}

plot(reducedDims(sce)$UMAP, col = colDat$Color, pch = 16, cex = 0.5)
lines(SlingshotDataSet(sce), lwd = 2, type = 'lineages', col = 'black')

```


### plot curve col cluster
```{r slingshot curve col cluster}

plot(reducedDims(sce)$UMAP, col = colDat$Color, pch = 16, cex = 0.5)
lines(SlingshotDataSet(sce), lwd = 2, col = 'black')


```

### plot curve col pseudotime
```{r slingshot curve col pseudotime}

colors <- colorRampPalette(brewer.pal(8,'OrRd'))(100)
plotcol <- colors[cut(sce$slingPseudotime_1, breaks=100)]
plotcol2 <- colors[cut(sce$slingPseudotime_2, breaks=100)]
plotcol3 <- colors[cut(sce$slingPseudotime_3, breaks=100)]
plotcol4 <- colors[cut(sce$slingPseudotime_4, breaks=100)]

plotColAll <- plotcol
plotColAll[which(is.na(plotColAll))] <- plotcol2[which(is.na(plotColAll))]
plotColAll[which(is.na(plotColAll))] <- plotcol3[which(is.na(plotColAll))]
plotColAll[which(is.na(plotColAll))] <- plotcol4[which(is.na(plotColAll))]

plot(reducedDims(sce)$UMAP, col = plotColAll, pch = 16, cex = 0.3)
lines(SlingshotDataSet(sce), lwd = 2, col = 'black')


```

## save sce object with pseudotime ordering
```{r save sce}
saveRDS(sce, file= paste0(basedir, "/data/TCRM_all10samplesMerged_sce.rds"))
#sce <- readRDS(paste0(basedir, "/data/TCRM_all10samplesMerged_sce.rds"))
```



```{r eval=FALSE, include=FALSE}
library(tradeSeq)
library(gam)

sceSub <- sce[, which(!is.na(sce$slingPseudotime_1))]
sceSub <- fitGAM(sceSub, parallel=T)

## subset sce to single lineage
sceSub <- sce[, which(!is.na(sce$slingPseudotime_1))]

# Only look at the 1,000 most variable genes when identifying temporally expressesd genes
Y <- log2(counts(sceSub) + 1)
var1K <- names(sort(apply(Y, 1, var),decreasing = TRUE))[1:1000]
Y <- Y[var1K, ]  # only counts for variable genes

# Fit GAM for each gene using pseudotime as independent variable.
t <- sceSub$slingPseudotime_1
gam.pval <- apply(Y, 1, function(z){
  d <- data.frame(z=z, t=t)
  tmp <- gam(z ~ lo(t), data=d)
  p <- summary(tmp)[4][[1]][1,5]
  p
})


# Identify genes with the most significant time-dependent model fit.
topgenes <- data.frame(gene=names(gam.pval), 
                       pVal=gam.pval)  

scater::plotHeatmap(sce, topgenes$gene)
# Prepare and plot a heatmap of the top genes that vary their expression over pseudotime.
library(clusterExperiment)
seurat <- as.Seurat(sceSub)
sceSel <- sceSub[which(rownames(sceSub) %in% topgenes),]
heatdata <- as.matrix(counts(sceSel), order(t, na.last = NA))
heatclus <- sceSel$seurat_clusters[order(t, na.last = NA)]
png(paste0(basedir, "/data/heatmap_time_genes.png"), width=10, height=10, units = "in", res=200)
ce <- ClusterExperiment(heatdata, heatclus, transformation = log1p)
clusterExperiment::plotHeatmap(ce, clusterSamplesData = "orderSamplesValue", visualizeData = 'transformed', cexRow = 1.5, fontsize = 15)
dev.off()

# l1 <- slingLineages(sce)
# sce <- fitGAM(sce, parallel=T)

```


## session info
```{r session info}
sessionInfo()
date()
```

