---
title: "DE genes treated versus untreated total cells"
author: "Mechthild Lütge"
date: "24 July 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(ggsci)
  library(pheatmap)
  library(ggpubr)
  library(scater)
  library(scran)
  library(viridis)
})

```


## heatmap function

```{r avg heatmap funct}
avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  
  selGenes <- selGenes$gene
  
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
  annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                       colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
    dplyr::mutate(cond = gsub(".*_","",col1)) %>%
    dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      cond = colVecCond,
      celltype=colVecIdent)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
    ordVec <- levels(seurat)
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0, cluster_rows = cr, 
         cluster_cols = cc,
         color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = annotation_col, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

```


## sign plot funct
```{r funct sign plot}

## random plotting order
shuf <- function(df){
  return(df[sample(1:dim(df)[1], dim(df)[1]),])
}


## adapted from CellMixS
visGroup_adapt <- function (sce,group,dim_red = "TSNE",col_group=pal_nejm()(8)) 
{
    if (!is(sce, "SingleCellExperiment")) {
        stop("Error:'sce' must be a 'SingleCellExperiment' object.")
    }
    if (!group %in% names(colData(sce))) {
        stop("Error: 'group' variable must be in 'colData(sce)'")
    }
    cell_names <- colnames(sce)
    if (!dim_red %in% "TSNE") {
        if (!dim_red %in% reducedDimNames(sce)) {
            stop("Please provide a dim_red method listed in reducedDims of sce")
        }
        red_dim <- as.data.frame(reducedDim(sce, dim_red))
    }
    else {
        if (!"TSNE" %in% reducedDimNames(sce)) {
            if ("logcounts" %in% names(assays(sce))) {
                sce <- runTSNE(sce)
            }
            else {
                sce <- runTSNE(sce, exprs_values = "counts")
            }
        }
        red_dim <- as.data.frame(reducedDim(sce, "TSNE"))
    }
    colnames(red_dim) <- c("red_dim1", "red_dim2")
    df <- data.frame(sample_id = cell_names, group_var = colData(sce)[, 
        group], red_Dim1 = red_dim$red_dim1, red_Dim2 = red_dim$red_dim2)
    t <- ggplot(shuf(df), aes_string(x = "red_Dim1", y = "red_Dim2")) + 
        xlab(paste0(dim_red, "_1")) + ylab(paste0(dim_red, "_2")) + 
        theme_void() + theme(aspect.ratio = 1,
                             panel.grid.minor = element_blank(), 
        panel.grid.major = element_line(color = "grey", size = 0.3))
    t_group <- t + geom_point(size = 1.5, alpha = 0.8,
                              aes_string(color = "group_var")) + 
        guides(color = guide_legend(override.aes = list(size = 1), 
            title = group)) + ggtitle(group)
    if (is.numeric(df$group_var)) {
        t_group <- t_group + scale_color_viridis(option = "D")
    }
    else {
        t_group <- t_group + scale_color_manual(values = col_group)
    }
    t_group
}



```


## set dir
```{r set dir}
basedir <- here()
seurat <- readRDS(file = paste0(basedir,
                      "/data/MuHeart_totalCellsPlusTreated_integratedLabeled", 
                      "_seurat.rds"))
Idents(seurat) <- seurat$label
seurat$age[which(seurat$treatment != "no")] <- "12wk"

```



## color vectors
```{r colVec}

colPal <- pal_igv()(length(levels(seurat)))
colGrp <- pal_jama()(length(unique(seurat$grp)))
colAge <- pal_uchicago()(length(unique(seurat$age)))
colStype <- pal_aaas()(length(unique(seurat$seqType)))
colDat <- c(pal_npg()(10),
            pal_futurama()(10))[1:(length(unique(seurat$dataset)))]
colTreat <- pal_jama()(length(unique(seurat$treatment)))

names(colPal) <- levels(seurat)
names(colGrp) <- unique(seurat$grp)
names(colAge) <- unique(seurat$age)
names(colStype) <- unique(seurat$seqType)
names(colDat) <- unique(seurat$dataset)
names(colTreat) <- unique(seurat$treatment)

colLab <- c("#5050FF", "#CE3D32", "#749B58", "#F0E685",
            "#466983", "#BA6388", "#5DB1DD", "#802268",
            "#6BD76B", "#D595A7", "#924822", "#837B8D",
            "#C75127", "#D58F5C", "#7A65A5", "#E4AF69")

names(colLab) <- c("InfMonos", "Tcells", "Endothelial", "Macrophages",
                   "Fibroblasts", "DCs", "NKcells", "Perivascular",
                   "Neutrophils", "Bcells", "Cardiomyocytes", "proliferating",
                   "pDCs", "endocardialEndothelial", "Eosinophils",
                   "GlialCells")
```

## subset on naive + treated + isotype
```{r subset seurat}
table(seurat$grp, seurat$treatment)
seurat <- subset(seurat, (treatment != "no" | grp == "control"))
table(seurat$grp, seurat$treatment)
```


## vis data {.tabset}

### group
```{r vis grp}

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```


### Age
```{r vis age}

DimPlot(seurat, reduction = "umap", group.by = "age", cols=colAge)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```


### SeqType
```{r vis seqType}

DimPlot(seurat, reduction = "umap", group.by = "seqType", cols=colStype)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

DimPlot(seurat, reduction = "umap", group.by = "seqType", cols=colStype)+
  theme_void() 
```

### Treatment
```{r vis treat}

DimPlot(seurat, reduction = "umap", group.by = "treatment", cols=colTreat)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

DimPlot(seurat, reduction = "umap", group.by = "treatment", cols=colTreat)+
  theme_void() 

```


### label
```{r vis label}

DimPlot(seurat, reduction = "umap", group.by = "label", cols=colLab)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

DimPlot(seurat, reduction = "umap", group.by = "label", cols=colLab)+
  theme_void() 

```




## diffusionmap all cells
```{r diffusion map all, fig.height=3.5, fig.width=5}

## all
sce <- as.SingleCellExperiment(seurat)
sce <- runDiffusionMap(sce)

p <- visGroup_adapt(sce, 'label', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colLab) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p

p <- visGroup_adapt(sce, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p

lapply(unique(sce$treatment), function(grpSub){
  sceSub2 <- sce[,which(sce$treatment == grpSub)]
  p <- visGroup_adapt(sceSub2, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
  p
})


## all only sc
seuratSub <- subset(seurat, seqType %in% c("sc"))

sceSub <- as.SingleCellExperiment(seuratSub)
sceSub <- runDiffusionMap(sceSub)

p <- visGroup_adapt(sceSub, 'label', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colLab) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p

p <- visGroup_adapt(sceSub, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p


lapply(unique(sceSub$treatment), function(grpSub){
  sceSub2 <- sceSub[,which(sceSub$treatment == grpSub)]
  p <- visGroup_adapt(sceSub2, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
  p
})

## all only sn
seuratSub <- subset(seurat, seqType %in% c("sn"))

sceSub <- as.SingleCellExperiment(seuratSub)
sceSub <- runDiffusionMap(sceSub)

p <- visGroup_adapt(sceSub, 'label', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colLab) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p

p <- visGroup_adapt(sceSub, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p


lapply(unique(sceSub$treatment), function(grpSub){
  sceSub2 <- sceSub[,which(sceSub$treatment == grpSub)]
  p <- visGroup_adapt(sceSub2, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
  p
})


```


## diffusionmap Fbroblasts
```{r diffusion map fibroblasts, fig.height=3.5, fig.width=5}

## only fibroblasts sn + sc
seuratSub <- subset(seurat, label %in% c("Fibroblasts"))

sceSub <- as.SingleCellExperiment(seuratSub)
sceSub <- runDiffusionMap(sceSub)

p <- visGroup_adapt(sceSub, 'label', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colLab) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p

p <- visGroup_adapt(sceSub, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p


lapply(unique(sceSub$treatment), function(grpSub){
  sceSub2 <- sceSub[,which(sceSub$treatment == grpSub)]
  p <- visGroup_adapt(sceSub2, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
  p
})

## only fibroblasts sn
seuratSub <- subset(seurat, label %in% c("Fibroblasts"))
seuratSub <- subset(seuratSub, seqType %in% c("sn"))

sceSub <- as.SingleCellExperiment(seuratSub)
sceSub <- runDiffusionMap(sceSub)

p <- visGroup_adapt(sceSub, 'label', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colLab) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p

p <- visGroup_adapt(sceSub, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p


lapply(unique(sceSub$treatment), function(grpSub){
  sceSub2 <- sceSub[,which(sceSub$treatment == grpSub)]
  p <- visGroup_adapt(sceSub2, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
  p
})

## only fibroblasts sc
seuratSub <- subset(seurat, label %in% c("Fibroblasts"))
seuratSub <- subset(seuratSub, seqType %in% c("sc"))

sceSub <- as.SingleCellExperiment(seuratSub)
sceSub <- runDiffusionMap(sceSub)

p <- visGroup_adapt(sceSub, 'label', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colLab) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p

p <- visGroup_adapt(sceSub, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
p


lapply(unique(sceSub$treatment), function(grpSub){
  sceSub2 <- sceSub[,which(sceSub$treatment == grpSub)]
  p <- visGroup_adapt(sceSub2, 'treatment', dim_red = 'DiffusionMap') +
    scale_colour_manual(values = colTreat) +
    theme_classic() + 
    theme(axis.text = element_blank(),
          axis.ticks = element_blank()) +
    labs(x='Dimension 1', y='Dimension 2')
  p
})

```



## session info
```{r session info}
sessionInfo()
date()
```




