---
title: "pseudotime analysis"
author: "Mechthild Lütge"
date: "6 Oct 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(SingleCellExperiment)
  library(scales)
  library(grDevices)
  library(RColorBrewer)
  library(pheatmap)
  library(ggsci)
  library(scater)
})

```

## set dir
```{r set dir}
basedir <- here()
seurat <- readRDS(file = paste0(basedir, 
                                "/data/TCRM_all10samplesMerged_seurat.rds"))

seurat$time_plus_grp <- paste0(seurat$time, "_", seurat$grp)
seurat <- subset(seurat, time == "12w", invert=T)
seurat <- rerunSeurat3(seurat)
```

## color vectors
```{r colVec}

colPal <- pal_igv()(length(levels(seurat)))
colGrp <- pal_jama()(length(unique(seurat$grp)))
colSmp <- c(pal_uchicago()(8), pal_npg()(8))[1:length(unique(seurat$dataset))]
colTime <- pal_npg()(length(unique(seurat$time)))

names(colPal) <- levels(seurat)
names(colGrp) <- unique(seurat$grp)
names(colSmp) <- unique(seurat$dataset)
names(colTime) <- unique(seurat$time)

```

## vis data {.tabset}
### clusters
```{r vis cluster}
DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### group
```{r vis grp}

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

```

### timepoint
```{r vis timepoint}

DimPlot(seurat, reduction = "umap", group.by = "time", cols=colTime)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### clustering res 0.4
```{r vis cluster res 0.4}

DimPlot(seurat, reduction = "umap", group.by = "RNA_snn_res.0.4", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

## save object
```{r save object}

saveRDS(seurat, file = paste0(basedir, 
                              "/data/TCRM_all10samplesMerged_wo12w_seurat.rds"))
```


## session info
```{r session info}
sessionInfo()
date()
```

