---
title: "Merge samples"
author: "Mechthild Lütge"
date: "14 May 2020"
output:
  html_document:
    self_contained: no
    code_folding: show
    number_sections: no
    toc: yes
    toc_depth: 3
    toc_float: true
    collapsed: no
    smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = c("png", "pdf"))
set.seed(1000)
```

## load packages
```{r libs}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(tidyverse)
  library(Seurat)
  library(magrittr)
  library(dplyr)
  library(purrr)
  library(ggplot2)
  library(here)
  library(runSeurat3)
  library(ggsci)
  library(ggpubr)
  library(pheatmap)
  library(RColorBrewer)
  library(CellMixS)
  library(scater)
  library(destiny)
})

```


## heatmap function

```{r avg heatmap funct}
avgHeatmap <- function(seurat, selGenes, colVecIdent, colVecCond=NULL,
                       ordVec=NULL, gapVecR=NULL, gapVecC=NULL,cc=FALSE,
                       cr=FALSE, condCol=FALSE){
  
  selGenes <- selGenes$gene
  
  ## assay data
  clusterAssigned <- as.data.frame(Idents(seurat)) %>%
  dplyr::mutate(cell=rownames(.))
  colnames(clusterAssigned)[1] <- "ident"
  seuratDat <- GetAssayData(seurat)
  
  ## genes of interest
  genes <- data.frame(gene=rownames(seurat)) %>% 
    mutate(geneID=gsub("^.*\\.", "", gene)) %>% filter(geneID %in% selGenes)

  ## matrix with averaged cnts per ident
  logNormExpres <- as.data.frame(t(as.matrix(
    seuratDat[which(rownames(seuratDat) %in% genes$gene),])))
  logNormExpres <- logNormExpres %>% dplyr::mutate(cell=rownames(.)) %>%
    dplyr::left_join(.,clusterAssigned, by=c("cell")) %>%
    dplyr::select(-cell) %>% dplyr::group_by(ident) %>%
    dplyr::summarise_all(mean)
  logNormExpresMa <- logNormExpres %>% dplyr::select(-ident) %>% as.matrix()
  rownames(logNormExpresMa) <- logNormExpres$ident
  logNormExpresMa <- t(logNormExpresMa)
  rownames(logNormExpresMa) <- gsub("^.*?\\.","",rownames(logNormExpresMa))
  
  ## remove genes if they are all the same in all groups
  ind <- apply(logNormExpresMa, 1, sd) == 0
  logNormExpresMa <- logNormExpresMa[!ind,]
  genes <- genes[!ind,]

  ## color columns according to cluster
  annotation_col <- as.data.frame(gsub("(^.*?_)","",
                                       colnames(logNormExpresMa)))%>%
    dplyr::mutate(celltype=gsub("(_.*$)","",colnames(logNormExpresMa)))
  colnames(annotation_col)[1] <- "col1"
  annotation_col <- annotation_col %>%
    dplyr::mutate(cond = gsub(".*_","",col1)) %>%
    dplyr::select(cond, celltype)
  rownames(annotation_col) <- colnames(logNormExpresMa) 

  ann_colors = list(
      cond = colVecCond,
      celltype=colVecIdent)
  if(is.null(ann_colors$cond)){
    annotation_col$cond <- NULL
  }
  
  ## adjust order
  logNormExpresMa <- logNormExpresMa[selGenes,]
  if(is.null(ordVec)){
    ordVec <- levels(seurat)
  }
  logNormExpresMa <- logNormExpresMa[,ordVec]

  ## scaled row-wise
  pheatmap(logNormExpresMa, scale="row" ,treeheight_row = 0, cluster_rows = cr, 
         cluster_cols = cc,
         color = colorRampPalette(c("#2166AC", "#F7F7F7", "#B2182B"))(50),
         annotation_col = annotation_col, cellwidth=15, cellheight=10,
         annotation_colors = ann_colors, gaps_row = gapVecR, gaps_col = gapVecC)
}

```



## set dir
```{r set dir}
basedir <- here()
seurat <- readRDS(file = paste0(basedir, 
                              "/data/TCRM_all10samplesMerged_wo12w_seurat.rds"))

seurat$time_plus_grp <- paste0(seurat$time, "_", seurat$grp)

## Remove cluster with cycling cells (mki67 high) and
## endothelial cells (Chdh5, Pecam1 high)
seurat <- subset(seurat, RNA_snn_res.0.4 %in% c("10", "11"), invert = T)
```


## color vectors
```{r colVec}

colPal <- pal_igv()(length(levels(seurat)))
colGrp <- pal_jama()(length(unique(seurat$grp)))
colSmp <- c(pal_uchicago()(8), pal_npg()(8))[1:length(unique(seurat$dataset))]
colTime <- pal_npg()(length(unique(seurat$time)))

names(colPal) <- levels(seurat)
names(colGrp) <- unique(seurat$grp)
names(colSmp) <- unique(seurat$dataset)
names(colTime) <- unique(seurat$time)

```


## vis data {.tabset}
### clusters
```{r vis cluster}
DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

DimPlot(seurat, reduction = "umap", cols=colPal)+
  theme_void() 
```

### group
```{r vis grp}

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

DimPlot(seurat, reduction = "umap", group.by = "grp", cols=colGrp)+
  theme_void() 


```


### Sample
```{r vis sample}

DimPlot(seurat, reduction = "umap", group.by = "dataset", cols=colSmp)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

DimPlot(seurat, reduction = "umap", group.by = "dataset", cols=colSmp)+
  theme_void() 

```

### batch
```{r vis batch}

DimPlot(seurat, reduction = "umap", group.by = "batch")+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")


```

### timepoint
```{r vis timepoint}

DimPlot(seurat, reduction = "umap", group.by = "time", cols=colTime)+
  theme_bw() +
  theme(axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.grid.minor = element_blank()) +
  xlab("UMAP1") +
  ylab("UMAP2")

DimPlot(seurat, reduction = "umap", group.by = "time", cols=colTime)+
  theme_void() 

```


### cnt Tab
```{r cnts par lab per seqType}

table(seurat$RNA_snn_res.0.4, seurat$grp)
```


## top 10 marker genes
```{r arker genes FB cluster, fig.height=18, fig.width=10}

Idents(seurat) <- seurat$RNA_snn_res.0.4

markerGenes <- FindAllMarkers(object = seurat, assay ="RNA",
                                     only.pos = TRUE, min.pct = 0.25,
                                     logfc.threshold = 0.25,
                                     test.use = "wilcox")


### plot DE genes top 10 avg logFC
DEGenesAll <- markerGenes %>% group_by(cluster) %>% 
  mutate(geneID = gene) %>% top_n(10, avg_log2FC) %>%
  mutate(gene=gsub(".*\\.", "",  geneID)) %>% 
  filter(nchar(gene)>1) 

ordDat <- levels(seurat$seurat_clusters)[which(
  levels(seurat$seurat_clusters) %in% unique(seurat$seurat_clusters))]
gapR <- c(seq(from=10, to=10*length(ordDat), by=10))

pOut <- avgHeatmap(seurat = seurat, selGenes = DEGenesAll,
                  colVecIdent = colPal, 
                  ordVec=ordDat,
                  gapVecR=gapR, gapVecC=NULL,cc=F,
                  cr=F, condCol=F)

```

## FB identity marker heatmap {.tabset}
### heatmap
```{r FB identity marker hm, fig.height=6, fig.width=8}
genes <- data.frame(geneID=rownames(seurat)) %>%
  mutate(gene=gsub("^.*\\.", "", geneID))
selGenes <- data.frame(gene=c("Nr4a1", "Pi16", "Pdpn", "Cd34", "Pdgfra",
                               "Col1a1")) %>%
  left_join(., genes, by="gene")

pOut <- avgHeatmap(seurat = seurat, selGenes = selGenes,
                  colVecIdent = colPal, 
                  ordVec=ordDat,
                  gapVecR=NULL, gapVecC=NULL,cc=F,
                  cr=F, condCol=F)

```


### vlnPlot
```{r FB identity marker vlnPlot}

pList <- sapply(selGenes$geneID, function(x){
  p <- VlnPlot(object = seurat, features = x,
               group.by = "RNA_snn_res.0.4",
               cols = colPal, pt.size = 0,
               fill.by = "ident"
               )
  plot(p)
})

```


## session info
```{r session info}
sessionInfo()
date()
```




